# Generated by Django 4.2.10 on 2024-02-24 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ('-id',), 'verbose_name': 'آدرس', 'verbose_name_plural': 'آدرس\u200cها'},
        ),
        migrations.AddField(
            model_name='address',
            name='post_code',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Post code'),
        ),
        migrations.AlterField(
            model_name='address',
            name='active',
            field=models.BooleanField(default=False, verbose_name='آدرس فعال'),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_line',
            field=models.CharField(max_length=255, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='address',
            name='province',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='استان'),
        ),
    ]
