# Generated by Django 4.2.10 on 2024-02-26 00:18

import apps.product.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CakeCream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
                ('added_price', models.PositiveIntegerField(default=0, verbose_name='Cake added price')),
            ],
            options={
                'verbose_name': 'Cake cream',
                'verbose_name_plural': 'Cake creams',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='CakeFilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
                ('added_price', models.PositiveIntegerField(default=0, verbose_name='Cake added price')),
            ],
            options={
                'verbose_name': 'Cake filling',
                'verbose_name_plural': 'Cake fillings',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='CakeSponge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
                ('added_price', models.PositiveIntegerField(default=0, verbose_name='Cake added price')),
            ],
            options={
                'verbose_name': 'Cake sponge',
                'verbose_name_plural': 'Cake sponges',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=128, verbose_name='Category title')),
            ],
            options={
                'verbose_name': 'Product category',
                'verbose_name_plural': 'Product categories',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=128, verbose_name='Tag title')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weight', models.DecimalField(decimal_places=1, default=1, max_digits=4, verbose_name='Weight')),
                ('description', models.CharField(blank=True, max_length=64, null=True, verbose_name='Short description')),
            ],
            options={
                'verbose_name': 'Weight',
                'verbose_name_plural': 'Weights',
            },
        ),
        migrations.CreateModel(
            name='CakeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('price', models.PositiveIntegerField(default=0, help_text='Per 1Kg', verbose_name='Price')),
                ('discount', models.PositiveSmallIntegerField(default=0, help_text='Percentage', verbose_name='Discount')),
                ('selling_price', models.PositiveIntegerField(default=0, help_text='Final price to pay', verbose_name='Selling price')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش')),
                ('code', models.CharField(blank=True, max_length=64, null=True, verbose_name='Product code')),
                ('on_display', models.BooleanField(default=False, verbose_name='is in display')),
                ('selling_weight', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Selling weight')),
                ('selling_stock', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Stock')),
                ('category', models.ManyToManyField(related_name='cake_products', to='product.category', verbose_name='Category')),
                ('cream', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.cakecream', verbose_name='Cream')),
                ('filling', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.cakefilling', verbose_name='Filling')),
                ('sponge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.cakesponge', verbose_name='Sponge')),
                ('tags', models.ManyToManyField(related_name='cake_tags', to='product.tag', verbose_name='Tags')),
                ('weights', models.ManyToManyField(related_name='cake_products', to='product.weight', verbose_name='Weights')),
            ],
            options={
                'verbose_name': 'Cake product',
                'verbose_name_plural': 'Cake products',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='CakeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to=apps.product.utils.product_images_path, verbose_name='Product image')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cake_images', to='product.cakeproduct', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Cake image',
                'verbose_name_plural': 'Cake images',
            },
        ),
    ]
