# Generated by Django 4.2 on 2024-04-07 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomProductAttrCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groups', models.ManyToManyField(blank=True, to='product.productattrgroup')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
