# Generated by Django 4.1 on 2023-12-08 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='type_name',
            new_name='title',
        ),
    ]
