# Generated by Django 4.1 on 2023-12-08 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_type_name_category_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('active', 'فعال'), ('disable', 'غیر فعال'), ('archived', 'ارشیو')], default='active', max_length=20),
        ),
    ]
