# Generated by Django 4.2 on 2024-04-07 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_customproductattrcategory_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customproduct',
            old_name='pictures',
            new_name='images',
        ),
    ]
