# Generated by Django 4.2 on 2024-04-09 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_rename_pictures_customproduct_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAttrSelected',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.simpleproductattr')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productattrgroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='ProductCartOption',
        ),
        migrations.AddField(
            model_name='customproduct',
            name='attr_selected',
            field=models.ManyToManyField(to='product.productattrselected'),
        ),
        migrations.AddField(
            model_name='productcart',
            name='attrs_selected',
            field=models.ManyToManyField(to='product.productattrselected'),
        ),
    ]
