# Generated by Django 4.2 on 2024-03-08 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_baseproduct_baseproductattr_productattrgroup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicproduct',
            name='type',
            field=models.CharField(choices=[('simple', 'simple'), ('showcase', 'showcase')], default='simple', max_length=12),
            preserve_default=False,
        ),
    ]
