# Generated by Django 4.2 on 2024-03-08 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_basicproduct_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='title',
        ),
    ]
