# Generated by Django 4.2 on 2024-04-09 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_productattrselected_delete_productcartoption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customproduct',
            name='writing_on',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
