# Generated by Django 4.2 on 2024-04-09 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_customproduct_writing_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomProductStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=12)),
                ('note', models.TextField(blank=True, null=True)),
                ('price', models.PositiveBigIntegerField(null=True)),
                ('custom_product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='product.customproduct')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
