# Generated by Django 4.2 on 2024-03-08 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_category_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicproduct',
            name='attr_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.productattrcategory'),
        ),
    ]
