# Generated by Django 4.2 on 2024-03-09 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_basicproduct_attr_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basicproduct',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
