# Generated by Django 4.2 on 2024-04-10 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_customproduct_options_customproductcart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customproductcart',
            name='custom_product',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to='product.customproduct'),
            preserve_default=False,
        ),
    ]
