# Generated by Django 4.2 on 2024-04-10 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_customproductcart_custom_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customproductcart',
            name='custom_product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart_item', to='product.customproduct'),
        ),
    ]
