# Generated by Django 4.2 on 2024-03-10 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_rename_description_comment_text_remove_comment_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseproduct',
            name='id',
            field=models.AutoField(default=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='baseproductattr',
            name='id',
            field=models.AutoField(default=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(default=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.AutoField(default=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='discountcoupon',
            name='id',
            field=models.AutoField(default=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productattrcategory',
            name='id',
            field=models.AutoField(default=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productattrgroup',
            name='id',
            field=models.AutoField(default=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productfavoritelist',
            name='id',
            field=models.AutoField(default=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='id',
            field=models.AutoField(default=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.AutoField(default=100, primary_key=True, serialize=False),
        ),
    ]
