# Generated by Django 4.2 on 2024-04-11 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_customproductcart_custom_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customproduct',
            old_name='attr_selected',
            new_name='attrs_selected',
        ),
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=15),
        ),
    ]
