# Generated by Django 4.2 on 2024-03-10 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_baseproduct_id_alter_baseproductattr_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
