# Generated by Django 4.2 on 2024-03-10 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_category_default'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('-default', '-id')},
        ),
    ]
