# Generated by Django 4.2 on 2024-03-10 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattrcategory',
            name='groups',
            field=models.ManyToManyField(blank=True, to='product.productattrgroup'),
        ),
    ]
