# Generated by Django 4.2 on 2024-03-11 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_productattrcategory_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseproductattr',
            name='group',
        ),
        migrations.AddField(
            model_name='productattrgroup',
            name='fields',
            field=models.ManyToManyField(to='product.simpleproductattr'),
        ),
    ]
