# Generated by Django 4.2 on 2024-03-12 02:18

import apps.product.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_remove_baseproductattr_group_productattrgroup_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcoupon',
            name='count',
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='simpleproductattr',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=apps.product.utils.get_upload_src_product_attr_pic),
        ),
    ]
