# Generated by Django 4.2 on 2024-04-17 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_alter_cartstatus_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ('-id',)},
        ),
    ]
