# Generated by Django 4.2 on 2024-03-12 02:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_alter_discountcoupon_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcoupon',
            name='expire_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
