# Generated by Django 4.2 on 2024-04-17 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_alter_cart_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartstatus',
            name='cart',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='product.cart'),
        ),
    ]
