# Generated by Django 4.2 on 2024-03-12 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_alter_discountcoupon_expire_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcoupon',
            name='expire_at',
            field=models.DateField(),
        ),
    ]
