# Generated by Django 4.2 on 2024-04-17 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_alter_cartstatus_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartstatus',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('cancelled', 'Cancelled'), ('in_progress', 'In_progress'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='pending', max_length=14),
        ),
    ]
