# Generated by Django 4.2 on 2024-04-17 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
        ('product', '0018_alter_cartstatus_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicproduct',
            name='image_cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_cover', to='storage.image'),
        ),
        migrations.AlterField(
            model_name='basicproduct',
            name='images',
            field=models.ManyToManyField(blank=True, to='storage.image'),
        ),
        migrations.AlterField(
            model_name='customproduct',
            name='images',
            field=models.ManyToManyField(to='storage.image'),
        ),
        migrations.AlterField(
            model_name='factorcakeimage',
            name='images',
            field=models.ManyToManyField(blank=True, to='storage.image'),
        ),
    ]
