# Generated by Django 4.2 on 2024-03-15 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('product', '0018_alter_discountcoupon_expire_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcoupon',
            name='code',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.CreateModel(
            name='FactorCakeImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_name', models.CharField(max_length=200)),
                ('factor_code', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('status', models.CharField(choices=[('seen', 'Seen'), ('unseen', 'Unseen')], max_length=8)),
                ('images', models.ManyToManyField(to='core.image')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
