# Generated by Django 4.2 on 2024-04-21 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_alter_basicproduct_image_cover_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsold',
            name='product',
        ),
        migrations.AddField(
            model_name='productsold',
            name='product_selected',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='product.productcart'),
            preserve_default=False,
        ),
    ]
