# Generated by Django 4.2 on 2024-03-15 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_alter_discountcoupon_code_factorcakeimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factorcakeimage',
            name='status',
            field=models.CharField(choices=[('seen', 'Seen'), ('unseen', 'Unseen')], default='unseen', max_length=8),
        ),
    ]
