# Generated by Django 4.2 on 2024-03-16 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0021_alter_factorcakeimage_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductView',
            fields=[
                ('baseproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.baseproduct')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.basicproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('product.baseproduct',),
        ),
    ]
