# Generated by Django 4.2 on 2024-04-22 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_factorcakeimage_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInventoryDefault',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.PositiveBigIntegerField()),
                ('quantity', models.PositiveBigIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
