# Generated by Django 4.2 on 2024-06-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_productsold_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinventory',
            name='display_price',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True),
        ),
    ]
