# Generated by Django 4.2 on 2024-06-26 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_productinventory_display_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomProductSweets',
            fields=[
                ('customproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.customproduct')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
            bases=('product.customproduct',),
        ),
        migrations.RemoveField(
            model_name='customproduct',
            name='type',
        ),
        migrations.RemoveField(
            model_name='customproduct',
            name='writing_on',
        ),
        migrations.CreateModel(
            name='CustomProductCake',
            fields=[
                ('customproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.customproduct')),
                ('type', models.CharField(choices=[('picture_on', 'Picture On'), ('model_on', 'Model On')], max_length=12)),
                ('writing_on', models.CharField(max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('product.customproduct',),
        ),
    ]
