# Generated by Django 4.2 on 2024-03-26 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0024_cart_alter_productview_user_productcart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattrcart',
            name='attr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.simpleproductattr'),
        ),
        migrations.AddField(
            model_name='productattrcart',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.productattrgroup'),
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('products', models.ManyToManyField(to='product.basicproduct')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
