# Generated by Django 4.2 on 2024-06-26 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_customproductsweets_remove_customproduct_type_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomProductAttrCategory',
            new_name='CustomProductCakeAttrCategory',
        ),
        migrations.CreateModel(
            name='CustomProductSweetsAttrCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, to='product.productattrgroup')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
