# Generated by Django 4.2 on 2024-06-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_image_created_at_image_updated_at_alter_image_id'),
        ('product', '0026_rename_customproductattrcategory_customproductcakeattrcategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customproduct',
            name='images',
        ),
        migrations.AddField(
            model_name='customproductcake',
            name='images',
            field=models.ManyToManyField(to='storage.image'),
        ),
    ]
