# Generated by Django 4.2 on 2024-07-07 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_remove_customproduct_images_customproductcake_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattrgroup',
            name='type_of_display',
            field=models.CharField(choices=[('row', 'Row'), ('column', 'Column'), ('box', 'Box')], default='row', max_length=7),
        ),
    ]
