# Generated by Django 4.2 on 2024-04-22 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_created_at_user_updated_at_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('normal_user', 'Normal User'), ('operator_user', 'Operator Admin'), ('super_user', 'Super Admin')], default='normal_user', max_length=20),
        ),
    ]
