# Generated by Django 4.2.10 on 2024-02-22 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/profiles/', verbose_name='تصویر پروفایل'),
        ),
    ]
