# Generated by Django 4.2 on 2024-04-14 23:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0012_discountcouponselected'),
        ('payment', '0002_alter_invoice_discount_selected_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='navigation.address'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='cart',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.cart'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='purchase',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.purchaseinvoice'),
        ),
        migrations.AlterField(
            model_name='manualinvoice',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.cart'),
        ),
        migrations.AlterField(
            model_name='manualinvoice',
            name='purchase',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.purchaseinvoice'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
