# Generated by Django 4.2 on 2024-04-17 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_invoice_address_alter_invoice_cart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='delivery_time',
            field=models.CharField(choices=[('fastest', 'سریعترین زمان ممکن'), ('until_completed', 'تا زمان تکمیل تمام محصولات')], max_length=20),
        ),
    ]
