# Generated by Django 4.2 on 2024-04-17 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_invoice_delivery_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='purchaseinvoice',
            options={'ordering': ('-id',)},
        ),
    ]
