# Generated by Django 4.2 on 2024-06-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_alter_invoice_options_alter_purchaseinvoice_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='delivery_time',
            field=models.CharField(choices=[('fastest', 'Fastest'), ('until_completed', 'Until completed')], max_length=20),
        ),
    ]
