# Generated by Django 4.2 on 2024-07-07 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_alter_invoice_delivery_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='delivery_time',
            field=models.CharField(choices=[('fastest', 'سریعترین زمان ممکن'), ('until_completed', 'تا زمان تکمیل تمام محصولات')], max_length=20),
        ),
    ]
