# Generated by Django 4.2 on 2024-03-10 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationuser',
            name='id',
            field=models.AutoField(default=100, primary_key=True, serialize=False),
        ),
    ]
