# Generated by Django 4.2 on 2024-03-10 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_alter_notificationuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationuser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
