# Generated by Django 4.2 on 2024-04-26 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_alter_notificationuser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationuser',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
