# Generated by Django 4.2 on 2024-06-27 12:44

import apps.public.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to=apps.public.models.get_upload_slider_src)),
            ],
        ),
    ]
